import styles from'./page.module.css'

import Head from 'next/head';
import ExampleSection from './components/ExampleSection';
import { Theme } from '@radix-ui/themes';



export default function Home() {
  return (
    
    <div>
   
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      
      <main>
        <ExampleSection />
      </main>
     
      
    </div>
   
    
  );
}
